### PR TITLE
Added the ability to enable filters to work with empty values

### PR DESCRIPTION
**Pull request by james-waring**
Hello, This is my first pull request so if there is anything i have missed please explain so i can learn.

I working on a project where i need to filter the model even when the value is an empty array. 

I have added a simple config value that will simply return the passed in input in removeEmptyInput.

If there is a better way you would like to do this would you still add it to the project?

### CODE REVIEW

**Comment by Tucker-Eric** [comment]
Hey @james-waring !

Thanks for the PR! I like the idea behind it. Do you think we'd be able to have the configuration live on the filter itself instead of in the config? I like the granular control you'd be able to have by just enabling it for filters your interested in.

**Comment by james-waring** [comment]
Hi, I like that idea too.

I have updated the code, it now has an array property called `allowedEmptyFilters` on the ModelFilter. 

When the `filterInput` function runs i now add the method name that was called to a `calledMethods` array so when the `allowedEmptyFiltersInput` function runs it will run the filters that are in the array `allowedEmptyFilters` but only if the method name is not in the `calledMethods` array.

As im not sure if i can get what methods have been called from the eloquent query builder i have done it this way for now. If this can be done then it probably would be better to swap it out to this code.

I have added the test `testAllowedEmptyFilter` but i had to leave it as a todo because i cant work out how to do it as i think the best thing to test is the query builder to make sure the method was called. 

Let me know what you think?

**Review by Tucker-Eric — APPROVED** [review]

**Comment by Tucker-Eric** [comment]
@james-waring , I added the tests and update the property to be boolean on the model filter to conditionally filter out the empty input when `true`.

**Comment by Tucker-Eric** [comment]
@james-waring published under the [3.4.0](https://github.com/Tucker-Eric/EloquentFilter/releases/tag/3.4.0) tag

**Pull request merged**
